services:
    database_github-ci:
        image: postgres
        container_name: database_github-ci
        restart: always
        ports:
            - "1234:5432"
        env_file:
            - .env.test

    node_github-ci:
        container_name: node_github-ci
        build: ./back-end
        ports:
            - 5000:5000
        depends_on:
            - database_github-ci
        env_file:
            - .env.test